# Generated by Django 5.2.5 on 2025-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VzhuhPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='vzhuhs_photos/')),
            ],
            options={
                'verbose_name': 'Фото Вжуха',
                'verbose_name_plural': 'Фотографии Вжуха',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Vzhuh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(help_text='Введите город вылета', max_length=100, verbose_name='Город вылета')),
                ('arrival_city', models.CharField(help_text='Введите город прибытия', max_length=100, verbose_name='Город прибытия')),
                ('description', models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание')),
                ('best_time_to_travel', models.TextField(blank=True, help_text='Введите лучшее время для поездки', null=True, verbose_name='Лучшее время для поездки')),
                ('suitable_for_whom', models.TextField(blank=True, help_text='Введите для кого подойдёт', null=True, verbose_name='Для кого подойдёт')),
                ('description_hotel', models.TextField(blank=True, help_text='Введите описание к отелям', null=True, verbose_name='Описание к отелям')),
                ('description_blog', models.TextField(blank=True, help_text='Введите описание к блогу', null=True, verbose_name='Описание к блогу')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован ли Вжух', verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата публикации', verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления', verbose_name='Дата обновления')),
                ('hotels', models.ManyToManyField(blank=True, help_text='Выберите отели', related_name='vzhuhs', to='hotels.hotel', verbose_name='Вжухнутые отели')),
                ('tours', models.ManyToManyField(blank=True, help_text='Выберите туры', related_name='vzhuhs', to='tours.tour', verbose_name='Вжухнутые туры')),
                ('photos', models.ManyToManyField(blank=True, help_text='Выберите фотографии Вжуха', related_name='vzhuhs', to='vzhuhs.vzhuhphoto', verbose_name='Фотографии Вжуха')),
            ],
            options={
                'verbose_name': 'Вжух',
                'verbose_name_plural': 'Вжухи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['departure_city'], name='vzhuhs_vzhu_departu_93fa0c_idx')],
            },
        ),
    ]
