# Generated by Django 5.2.4 on 2025-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_longitude_alter_hotel_user_rating_and_more'),
        ('tours', '0002_initial'),
        ('vzhuhs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vzhuh',
            name='arrival_city',
            field=models.CharField(help_text='Введите город прибытия', max_length=100, verbose_name='Город прибытия'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='best_time_to_travel',
            field=models.TextField(blank=True, help_text='Введите лучшее время для поездки', null=True, verbose_name='Лучшее время для поездки'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата публикации', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='departure_city',
            field=models.CharField(help_text='Введите город вылета', max_length=100, verbose_name='Город вылета'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='description_blog',
            field=models.TextField(blank=True, help_text='Введите описание к блогу', null=True, verbose_name='Описание к блогу'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='description_hotel',
            field=models.TextField(blank=True, help_text='Введите описание к отелям', null=True, verbose_name='Описание к отелям'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='hotels',
            field=models.ManyToManyField(blank=True, help_text='Выберите отели', related_name='vzhuhs', to='hotels.hotel', verbose_name='Вжухнутые отели'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Опубликован ли Вжух', verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Выберите фотографии Вжуха', related_name='vzhuhs', to='vzhuhs.vzhuhphoto', verbose_name='Фотографии Вжуха'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='suitable_for_whom',
            field=models.TextField(blank=True, help_text='Введите для кого подойдёт', null=True, verbose_name='Для кого подойдёт'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='tours',
            field=models.ManyToManyField(blank=True, help_text='Выберите туры', related_name='vzhuhs', to='tours.tour', verbose_name='Вжухнутые туры'),
        ),
        migrations.AlterField(
            model_name='vzhuh',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата обновления', verbose_name='Дата обновления'),
        ),
    ]
