# Generated by Django 5.2.3 on 2025-06-30 14:28

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Телефон в формате: +7 (XXX) XXX-XX-XX', max_length=128, region='RU', verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Аватар')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Документы')),
                ('role', models.CharField(choices=[('USER', 'Пользователь'), ('TOUR_OPERATOR', 'Туроператор'), ('HOTELIER', 'Отельер'), ('ADMIN', 'Администратор')], default='USER', verbose_name='Роль пользователя')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('EUR', 'Евро'), ('USD', 'Доллар')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('language', models.CharField(choices=[('RU', 'Русский'), ('EN', 'Английский')], default='RU', max_length=2, verbose_name='Язык интерфейса')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Получать оповещения')),
                ('preferred_contact_channel', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email')], default='email', max_length=10, verbose_name='Приоритетный канал связи')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-pk',),
            },
        ),
    ]
