# Generated by Django 5.1.4 on 2024-12-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("tour_operator", "Туроператор"),
                    ("regular_user", "Пользователь"),
                ],
                default="regular_user",
                max_length=20,
            ),
        ),
    ]
