# Generated by Django 5.1.4 on 2024-12-17 14:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_number_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Номер телефона в формате: +7 (999) 999-99-99",
                max_length=128,
                region="RU",
                verbose_name="Телефон",
            ),
        ),
    ]
