# Generated by Django 5.2.4 on 2025-08-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_ban_level_user_ban_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ban_level",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Уровень бана"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ban_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Блокировка до (числа)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Счетчик ошибок входа"
            ),
        ),
    ]
