# Generated by Django 5.2.4 on 2025-08-12 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_loginattempt_ts_to_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loginattempt",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Попытка входа",
                "verbose_name_plural": "Попытки входа",
            },
        ),
        migrations.RemoveIndex(
            model_name="loginattempt",
            name="users_login_user_id_3ed05d_idx",
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="success",
            field=models.BooleanField(verbose_name="Успех"),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["user", "-created_at"], name="users_login_user_id_685c23_idx"
            ),
        ),
    ]
