# Generated by Django 5.2.4 on 2025-08-08 09:58

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите email", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Формат: +X XXX XXX XX XX",
                        max_length=128,
                        region="RU",
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "visa_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Введите количество виз",
                        null=True,
                        verbose_name="Количество виз",
                    ),
                ),
                (
                    "visa_price_per_one",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите цену за одного человека",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Цена за одного человека",
                    ),
                ),
                (
                    "visa_total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите общую стоимость виз",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость виз",
                    ),
                ),
                (
                    "med_insurance_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Введите количество медицинских страховок",
                        null=True,
                        verbose_name="Количество медицинских страховок",
                    ),
                ),
                (
                    "med_insurance_price_per_one",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите цену за одного человека",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Цена за одного человека",
                    ),
                ),
                (
                    "med_insurance_total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите общую стоимость медицинских страховок",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость медицинских страховок",
                    ),
                ),
                (
                    "cancellation_insurance_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите общую стоимость страховок от невыезда",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость страховок от невыезда",
                    ),
                ),
                (
                    "wishes",
                    models.TextField(
                        blank=True,
                        help_text="Введите данные по пожеланиям",
                        null=True,
                        verbose_name="Пожелания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Подтвержден", "Подтвержден"),
                            ("Ожидает подтверждения", "Ожидает подтверждения"),
                            ("Необходимо связаться", "Необходимо связаться"),
                        ],
                        default="Ожидает подтверждения",
                        help_text="Выберите статус заявки",
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Общая стоимость",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на тур",
                "verbose_name_plural": "Заявки на тур",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="ApplicationHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите email", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Формат: +X XXX XXX XX XX",
                        max_length=128,
                        region="RU",
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "visa_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Введите количество виз",
                        null=True,
                        verbose_name="Количество виз",
                    ),
                ),
                (
                    "visa_price_per_one",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите цену за одного человека",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Цена за одного человека",
                    ),
                ),
                (
                    "visa_total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите общую стоимость виз",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость виз",
                    ),
                ),
                (
                    "med_insurance_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Введите количество медицинских страховок",
                        null=True,
                        verbose_name="Количество медицинских страховок",
                    ),
                ),
                (
                    "med_insurance_price_per_one",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите цену за одного человека",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Цена за одного человека",
                    ),
                ),
                (
                    "med_insurance_total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите общую стоимость медицинских страховок",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость медицинских страховок",
                    ),
                ),
                (
                    "cancellation_insurance_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Введите общую стоимость страховок от невыезда",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость страховок от невыезда",
                    ),
                ),
                (
                    "wishes",
                    models.TextField(
                        blank=True,
                        help_text="Введите данные по пожеланиям",
                        null=True,
                        verbose_name="Пожелания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Подтвержден", "Подтвержден"),
                            ("Ожидает подтверждения", "Ожидает подтверждения"),
                            ("Необходимо связаться", "Необходимо связаться"),
                        ],
                        default="Ожидает подтверждения",
                        help_text="Выберите статус заявки",
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Общая стоимость",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999.99")
                            ),
                        ],
                        verbose_name="Общая стоимость",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите отель",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotel_applications",
                        to="hotels.hotel",
                        verbose_name="Отель",
                    ),
                ),
                (
                    "quantity_guests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите гостей",
                        related_name="%(class)s_guests",
                        to="guests.guest",
                        verbose_name="Гости",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на отель",
                "verbose_name_plural": "Заявки на отель",
                "ordering": ("-pk",),
            },
        ),
    ]
