# Generated by Django 5.1.4 on 2024-12-14 10:27

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Введите дату начала тура",
                        verbose_name="Дата начала тура",
                    ),
                ),
                ("end_date", models.DateField(verbose_name="Дата окончания тура")),
                (
                    "airline",
                    models.CharField(max_length=50, verbose_name="Авиакомпания"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите email", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Введите номер телефона",
                        max_length=128,
                        region="RU",
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "visa",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оформление визы",
                    ),
                ),
                (
                    "med_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Медицинская страховка"
                    ),
                ),
                (
                    "cancellation_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Страховка невыезда"
                    ),
                ),
                (
                    "wishes",
                    models.TextField(
                        blank=True,
                        help_text="Введите пожелания",
                        null=True,
                        verbose_name="Пожелания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Подтвержден", "Подтвержден"),
                            ("Ожидает подтверждения", "Ожидает подтверждения"),
                            ("Необходимо связаться", "Необходимо связаться"),
                        ],
                        default="Ожидает подтверждения",
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotels.hotel",
                        verbose_name="Отель",
                    ),
                ),
                (
                    "quantity_rooms",
                    models.ManyToManyField(
                        blank=True,
                        to="hotels.hotelroom",
                        verbose_name="Количество номеров",
                    ),
                ),
                (
                    "quantity_guests",
                    models.ManyToManyField(
                        blank=True,
                        to="applications.guest",
                        verbose_name="Количество гостей",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ("-pk",),
            },
        ),
    ]
