# Generated by Django 5.2.5 on 2025-09-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhotel',
            name='quantity_guests',
            field=models.ManyToManyField(blank=True, help_text='Выберите гостей', related_name='%(class)s_guests', to='guests.guest', verbose_name='Гости'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Выберите номер', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_applications', to='rooms.room', verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='quantity_guests',
            field=models.ManyToManyField(blank=True, help_text='Выберите гостей', related_name='%(class)s_guests', to='guests.guest', verbose_name='Гости'),
        ),
    ]
