# Generated by Django 5.2.3 on 2025-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhotel',
            name='quantity_guests',
            field=models.ManyToManyField(blank=True, help_text='Выберите гостей', related_name='%(class)s_guests', to='guests.guest', verbose_name='Гости'),
        ),
    ]
