# Generated by Django 5.2.5 on 2025-09-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtour',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Выберите тур', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_applications', to='tours.tour', verbose_name='Тур'),
        ),
    ]
