# Generated by Django 5.2.3 on 2025-06-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhotel',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Выберите номер', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_applications', to='rooms.room', verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='med_insurance',
            field=models.ForeignKey(blank=True, help_text='Введите данные по медицинской страховке', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.applicationmedicalinsurance', verbose_name='Медицинская страховка'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='cancellation_insurance',
            field=models.ForeignKey(blank=True, help_text='Введите данные по страховке невыезда', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.applicationcancellationinsurance', verbose_name='Страховка невыезда'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='med_insurance',
            field=models.ForeignKey(blank=True, help_text='Введите данные по медицинской страховке', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.applicationmedicalinsurance', verbose_name='Медицинская страховка'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='quantity_guests',
            field=models.ManyToManyField(blank=True, help_text='Выберите гостей', related_name='%(class)s_guests', to='guests.guest', verbose_name='Гости'),
        ),
    ]
