# Generated by Django 5.2.3 on 2025-06-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtour',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Выберите тур', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_applications', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='visa',
            field=models.ForeignKey(blank=True, help_text='Введите данные по визе', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.applicationvisa', verbose_name='Оформление визы'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='visa',
            field=models.ForeignKey(blank=True, help_text='Введите данные по визе', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.applicationvisa', verbose_name='Оформление визы'),
        ),
    ]
