# Generated by Django 5.2.4 on 2025-07-21 18:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationhotel',
            name='cancellation_insurance',
        ),
        migrations.RemoveField(
            model_name='applicationtour',
            name='cancellation_insurance',
        ),
        migrations.RemoveField(
            model_name='applicationhotel',
            name='med_insurance',
        ),
        migrations.RemoveField(
            model_name='applicationtour',
            name='med_insurance',
        ),
        migrations.RemoveField(
            model_name='applicationtour',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='applicationhotel',
            name='visa',
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='cancellation_insurance_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите общую стоимость страховок от невыезда', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Общая стоимость страховок от невыезда'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='med_insurance_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите количество медицинских страховок', null=True, verbose_name='Количество медицинских страховок'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='med_insurance_price_per_one',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену за одного человека', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Цена за одного человека'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='med_insurance_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите общую стоимость медицинских страховок', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Общая стоимость медицинских страховок'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='visa_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите количество виз', null=True, verbose_name='Количество виз'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='visa_price_per_one',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену за одного человека', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Цена за одного человека'),
        ),
        migrations.AddField(
            model_name='applicationhotel',
            name='visa_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите общую стоимость виз', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Общая стоимость виз'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='cancellation_insurance_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите общую стоимость страховок от невыезда', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Общая стоимость страховок от невыезда'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='med_insurance_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите количество медицинских страховок', null=True, verbose_name='Количество медицинских страховок'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='med_insurance_price_per_one',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену за одного человека', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Цена за одного человека'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='med_insurance_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите общую стоимость медицинских страховок', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Общая стоимость медицинских страховок'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='visa_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите количество виз', null=True, verbose_name='Количество виз'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='visa_price_per_one',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену за одного человека', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Цена за одного человека'),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='visa_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите общую стоимость виз', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Общая стоимость виз'),
        ),
        migrations.DeleteModel(
            name='ApplicationCancellationInsurance',
        ),
        migrations.DeleteModel(
            name='ApplicationMedicalInsurance',
        ),
        migrations.DeleteModel(
            name='ApplicationVisa',
        ),
    ]
