# Generated by Django 5.2.3 on 2025-06-30 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrules',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем'),
        ),
        migrations.AddField(
            model_name='room',
            name='rules',
            field=models.ManyToManyField(help_text='Введите название правила, а потом выберите его возможность использования Да/Нет', related_name='rooms', to='rooms.roomrules', verbose_name='Название правила'),
        ),
    ]
