# Generated by Django 5.2.4 on 2025-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdate',
            name='categories',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('hotel',), 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.RemoveField(
            model_name='roomrules',
            name='created_by',
        ),
        migrations.AddField(
            model_name='room',
            name='calendar_dates',
            field=models.ManyToManyField(blank=True, help_text='Календарь бронирования', related_name='rooms_dates', through='calendars.CalendarPrice', to='calendars.calendardate', verbose_name='Календарь бронирования'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Twin Room', 'Twin Room'), ('Triple Room', 'Triple Room'), ('Family Room', 'Family Room'), ('Superior Room', 'Superior Room'), ('Deluxe Room', 'Deluxe Room'), ('Studio', 'Studio'), ('Suite', 'Suite'), ('Junior Suite', 'Junior Suite'), ('Residence', 'Residence'), ('Royal Suite', 'Royal Suite'), ('Penthouse', 'Penthouse')], help_text='Категория номера', max_length=100, null=True, verbose_name='Категория номера'),
        ),
        migrations.DeleteModel(
            name='RoomCategory',
        ),
        migrations.DeleteModel(
            name='RoomDate',
        ),
    ]
