# Generated by Django 5.2.4 on 2025-08-08 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_alter_user_ban_level_alter_user_ban_until_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurances",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="insurance",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "medical",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Т-Страхование", "Т-Страхование"),
                            ("Совкомбанк Страхование", "Совкомбанк Страхование"),
                            ("Сбербанк Страхование", "Сбербанк Страхование"),
                            ("ВСК Страхование", "ВСК Страхование"),
                            ("Росгорстрах", "Росгорстрах"),
                            ("РЕСО Страхование", "РЕСО Страхование"),
                            ("Согласие", "Согласие"),
                            ("СОГАЗ", "СОГАЗ"),
                            ("Альфа Страхование", "Альфа Страхование"),
                            ("Ренессанс Страхование", "Ренессанс Страхование"),
                            ("Ингострах", "Ингострах"),
                            ("INTOUCH", "INTOUCH"),
                            ("Не выбрано", "Не выбрано"),
                        ],
                        default="",
                        help_text="Медицинская страховка",
                        null=True,
                        verbose_name="Медицинская страховка",
                    ),
                ),
                (
                    "not_leaving",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("СОГАЗ", "СОГАЗ"),
                            ("Т-Страхование", "Т-Страхование"),
                            ("Совкомбанк Страхование", "Совкомбанк Страхование"),
                            ("Сбербанк Страхование", "Сбербанк Страхование"),
                            ("ВСК Страхование", "ВСК Страхование"),
                            ("Росгорстрах", "Росгорстрах"),
                            ("РЕСО Страхование", "РЕСО Страхование"),
                            ("Согласие", "Согласие"),
                            ("Альфа Страхование", "Альфа Страхование"),
                            ("Ренессанс Страхование", "Ренессанс Страхование"),
                            ("Ингострах", "Ингострах"),
                            ("INTOUCH", "INTOUCH"),
                            ("Не выбрано", "Не выбрано"),
                        ],
                        default="",
                        help_text="Страховка от невыезда",
                        null=True,
                        verbose_name="Страховка от невыезда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страховка",
                "verbose_name_plural": "Страховки",
            },
        ),
    ]
