# Generated by Django 5.2.4 on 2025-07-03 11:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0002_alter_hotel_longitude_alter_hotel_user_rating_and_more'),
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Введите дату в формате YYYY-MM-DD', verbose_name='Начало периода стоимости категорий номеров')),
                ('end_date', models.DateField(help_text='Введите дату в формате YYYY-MM-DD', verbose_name='Конец периода стоимости категорий номеров')),
                ('available_for_booking', models.BooleanField(default=True, help_text='Доступность категории для бронирования в этот период', verbose_name='Доступна для бронирования')),
                ('discount', models.BooleanField(default=False, help_text='Применяется ли скидка на период', verbose_name='Акция')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина. Например 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей.', max_digits=8, null=True, verbose_name='Размер скидки')),
                ('hotel', models.ForeignKey(blank=True, help_text='Отель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_dates', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Календарь стоимости номеров',
                'verbose_name_plural': 'Календари стоимости номеров',
            },
        ),
        migrations.CreateModel(
            name='CalendarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Введите стоимость категории номеров в сутки', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Стоимость категории номеров в сутки')),
                ('calendar_date', models.ForeignKey(help_text='Календарь стоимости номеров', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_prices', to='calendars.calendardate', verbose_name='Календарь стоимости номеров')),
                ('room', models.ForeignKey(help_text='Номер', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_prices', to='rooms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
            },
        ),
    ]
