# Generated by Django 5.2.4 on 2025-08-08 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendars", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarprice",
            name="room",
            field=models.ForeignKey(
                help_text="Номер",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_prices",
                to="rooms.room",
                verbose_name="Номер",
            ),
        ),
        migrations.AddIndex(
            model_name="calendardate",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_calendardate_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarprice",
            index=models.Index(
                fields=["room", "calendar_date"], name="idx_calendarprice_room"
            ),
        ),
    ]
