# Generated by Django 5.2.4 on 2025-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('hotels', '0002_alter_hotel_longitude_alter_hotel_user_rating_and_more'),
        ('rooms', '0003_remove_roomdate_categories_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_calendardate_dates'),
        ),
        migrations.AddIndex(
            model_name='calendarprice',
            index=models.Index(fields=['room', 'calendar_date'], name='idx_calendarprice_room'),
        ),
    ]
