# Generated by Django 5.2.5 on 2025-09-01 18:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фотографию для промокода', null=True, upload_to='promocodes/photos/', verbose_name='Фотография для промокода')),
                ('start_date', models.DateField(help_text='Введите дату начала', verbose_name='Дата начала')),
                ('end_date', models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания')),
                ('name', models.CharField(help_text='Введите название для промокода', max_length=50, verbose_name='Название промокода')),
                ('code', models.CharField(help_text='Введите промокод (2-10 заглавных букв и 1-4 цифры). Разрешены только латинские заглавные буквы и цифры, остальное - запрещено', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Промокод должен содержать от 2 до 10 заглавных латинских букв и от 1 до 4 цифр. Всё остальное - запрещено.', regex='^[A-Z]{2,10}\\d{1,4}$')], verbose_name='Промокод')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина. Например 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))], verbose_name='Величина скидки')),
                ('description', models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Промокод активен', verbose_name='Активен')),
                ('hotels', models.ManyToManyField(blank=True, help_text='Отели', to='hotels.hotel', verbose_name='Отели')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
