# Generated by Django 5.2.4 on 2025-07-03 11:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0002_alter_hotel_longitude_alter_hotel_user_rating_and_more'),
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина, к примеру 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))], verbose_name='Величина скидки')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('hotels', models.ManyToManyField(blank=True, help_text='Отели', to='hotels.hotel', verbose_name='Отели')),
                ('tours', models.ManyToManyField(blank=True, help_text='Туры', to='tours.tour', verbose_name='Туры')),
            ],
        ),
        migrations.CreateModel(
            name='PromocodePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promocodes/')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_image', to='promocodes.promocode')),
            ],
        ),
    ]
