# Generated by Django 5.2.4 on 2025-07-21 18:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='promocodephoto',
            options={'verbose_name': 'Фотография промокода', 'verbose_name_plural': 'Фотографии промокодов'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(help_text='Введите промокод (3-10 заглавных букв и 1-4 цифры). Разрешены только латинские заглавные буквы и цифры, остальное - запрещено', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Промокод должен содержать от 3 до 10 заглавных латинских букв и от 1 до 4 цифр. Всё остальное - запрещено.', regex='^[A-Z]{3,10}\\d{1,4}$')], verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина. Например 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))], verbose_name='Величина скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end_date',
            field=models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Промокод активен', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(help_text='Введите название для промокода', max_length=50, verbose_name='Название промокода'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(help_text='Введите дату начала', verbose_name='Дата начала'),
        ),
    ]
