# Generated by Django 5.2.5 on 2025-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocodes', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='tours',
            field=models.ManyToManyField(blank=True, help_text='Туры', to='tours.tour', verbose_name='Туры'),
        ),
    ]
