# Generated by Django 5.1.4 on 2024-12-17 17:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HotelAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Удобство")),
            ],
            options={
                "verbose_name": "Удобство в отеле",
                "verbose_name_plural": "Удобства в отеле",
            },
        ),
        migrations.CreateModel(
            name="HotelPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="hotels/hotels/", verbose_name="Фотография отеля"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография отеля",
                "verbose_name_plural": "Фотографии отеля",
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Удобство")),
            ],
            options={
                "verbose_name": "Удобство в номере",
                "verbose_name_plural": "Удобства в номерах",
            },
        ),
        migrations.CreateModel(
            name="RoomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Категория номера"),
                ),
            ],
            options={
                "verbose_name": "Категория номера",
                "verbose_name_plural": "Категории номеров",
            },
        ),
        migrations.CreateModel(
            name="RoomPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="hotels/hotels/rooms/",
                        verbose_name="Фотография номера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография номера",
                "verbose_name_plural": "Фотографии номера",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название отеля"),
                ),
                (
                    "star_category",
                    models.IntegerField(
                        help_text="Выберите категорию отеля (от 0 до 5)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Категория отеля",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("Отель", "Отель"),
                            ("Хостел", "Хостел"),
                            ("Вилла", "Вилла"),
                            ("Апартаменты", "Апартаменты"),
                            ("Гостевой дом", "Гостевой дом"),
                            ("Гостиница", "Гостиница"),
                        ],
                        default="Отель",
                        max_length=13,
                        verbose_name="Тип размещения",
                    ),
                ),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Адрес отеля"),
                ),
                (
                    "distance_to_sea",
                    models.IntegerField(
                        blank=True,
                        help_text="Введите расстояние до моря в метрах",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Расстояние до моря",
                    ),
                ),
                (
                    "distance_to_airport",
                    models.IntegerField(
                        blank=True,
                        help_text="Введите расстояние до аэропорта в метрах",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200000),
                        ],
                        verbose_name="Расстояние до аэропорта",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание отеля")),
                (
                    "user_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Пользовательская оценка",
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(
                        choices=[
                            (datetime.time(14, 0), "14:00"),
                            (datetime.time(15, 0), "15:00"),
                            (datetime.time(16, 0), "16:00"),
                            (datetime.time(17, 0), "17:00"),
                            (datetime.time(18, 0), "18:00"),
                            (datetime.time(19, 0), "19:00"),
                            (datetime.time(20, 0), "20:00"),
                            (datetime.time(21, 0), "21:00"),
                            (datetime.time(22, 0), "22:00"),
                            (datetime.time(23, 0), "23:00"),
                            (datetime.time(0, 0), "00:00"),
                        ],
                        default=datetime.time(14, 0),
                        max_length=8,
                        verbose_name="Время заезда",
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        choices=[
                            (datetime.time(12, 0), "12:00"),
                            (datetime.time(11, 0), "11:00"),
                            (datetime.time(10, 0), "10:00"),
                            (datetime.time(9, 0), "09:00"),
                            (datetime.time(8, 0), "08:00"),
                            (datetime.time(7, 0), "07:00"),
                            (datetime.time(6, 0), "06:00"),
                            (datetime.time(5, 0), "05:00"),
                            (datetime.time(4, 0), "04:00"),
                            (datetime.time(3, 0), "03:00"),
                            (datetime.time(2, 0), "02:00"),
                            (datetime.time(1, 0), "01:00"),
                            (datetime.time(0, 0), "00:00"),
                        ],
                        default=datetime.time(12, 0),
                        max_length=8,
                        verbose_name="Время выезда",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        to="hotels.hotelamenity",
                        verbose_name="Удобства в отеле",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True,
                        to="hotels.hotelphoto",
                        verbose_name="Фотографии отеля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отель",
                "verbose_name_plural": "Отели",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food",
                    models.CharField(
                        choices=[
                            ("Без питания", "Без питания"),
                            ("Ultra all inclusive", "Ultra all inclusive"),
                            ("All inclusive", "All inclusive"),
                            ("Полный пансион", "Полный пансион"),
                            ("Полупансион", "Полупансион"),
                            ("Только завтраки", "Только завтраки"),
                        ],
                        default="Только завтраки",
                        max_length=30,
                        verbose_name="Тип питания",
                    ),
                ),
                (
                    "type_of_holiday",
                    models.CharField(
                        choices=[
                            ("Пляжный", "Пляжный"),
                            ("Городской", "Городской"),
                            ("Спа", "Спа"),
                            ("Лечебный", "Лечебный"),
                            ("С детьми", "С детьми"),
                            ("С животными", "С животными"),
                        ],
                        default="Пляжный",
                        max_length=15,
                        verbose_name="Тип отдыха",
                    ),
                ),
                (
                    "smoking",
                    models.BooleanField(
                        default=False, verbose_name="Курение разрешено?"
                    ),
                ),
                (
                    "pet",
                    models.BooleanField(
                        default=False, verbose_name="С животными разрешено?"
                    ),
                ),
                (
                    "area",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Площадь номера",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Количество проживающих людей",
                    ),
                ),
                (
                    "single_bed",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Односпальная кровать",
                    ),
                ),
                (
                    "double_bed",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Двуспальная кровать",
                    ),
                ),
                (
                    "nightly_price",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name="Цена за ночь",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotels.hotel",
                        verbose_name="Отель",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        to="hotels.roomamenity",
                        verbose_name="Удобства в номере",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotels.roomcategory",
                        verbose_name="Категория номера",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True,
                        to="hotels.roomphoto",
                        verbose_name="Фотографии номера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
                "ordering": ("category",),
            },
        ),
    ]
