# Generated by Django 5.1.4 on 2024-12-12 08:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmenityRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите удобство",
                        max_length=50,
                        verbose_name="Удобство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Удобство в номере",
                "verbose_name_plural": "Удобства в номерах",
            },
        ),
        migrations.CreateModel(
            name="PlaceHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Выберите тип размещения",
                        max_length=15,
                        verbose_name="Тип размещения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип размещения",
                "verbose_name_plural": "Типы размещения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AmenityHotel",
            fields=[
                (
                    "amenityroom_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hotels.amenityroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Удобство в отеле",
                "verbose_name_plural": "Удобства в отеле",
            },
            bases=("hotels.amenityroom",),
        ),
        migrations.CreateModel(
            name="HotelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Стандарт", "Стандарт"),
                            ("Комфорт", "Комфорт"),
                            ("Семейный", "Семейный"),
                            ("Люкс", "Люкс"),
                        ],
                        default="Стандарт",
                        help_text="Выберите категорию номера",
                        max_length=20,
                        verbose_name="Категория номера",
                    ),
                ),
                (
                    "food",
                    models.CharField(
                        choices=[
                            ("Без питания", "Без питания"),
                            ("Ultra all inclusive", "Ultra all inclusive"),
                            ("All inclusive", "All inclusive"),
                            ("Полный пансион", "Полный пансион"),
                            ("Полупансион", "Полупансион"),
                            ("Только завтраки", "Только завтраки"),
                        ],
                        default="Только завтраки",
                        help_text="Выберите тип питания",
                        max_length=30,
                        verbose_name="Тип питания",
                    ),
                ),
                (
                    "type_of_holiday",
                    models.CharField(
                        choices=[
                            ("Пляжный", "Пляжный"),
                            ("Городской", "Городской"),
                            ("С детьми", "С детьми"),
                            ("С животными", "С животными"),
                        ],
                        default="Пляжный",
                        help_text="Выберите тип отдыха",
                        max_length=15,
                        verbose_name="Тип отдыха",
                    ),
                ),
                (
                    "smoking",
                    models.CharField(
                        choices=[
                            ("Разрешено", "Разрешено"),
                            ("Запрещено", "Запрещено"),
                        ],
                        default="Запрещено",
                        help_text="Выберите курение",
                        max_length=20,
                        verbose_name="Курение",
                    ),
                ),
                (
                    "pet",
                    models.CharField(
                        choices=[
                            ("Разрешено", "Разрешено"),
                            ("Запрещено", "Запрещено"),
                        ],
                        default="Разрешено",
                        help_text="Выберите с животными можно?",
                        max_length=20,
                        verbose_name="С животными можно?",
                    ),
                ),
                (
                    "area",
                    models.PositiveIntegerField(
                        help_text="Введите площадь номера",
                        verbose_name="Площадь номера",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию номера",
                        null=True,
                        upload_to="hotels/rooms/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Введите количество проживающих людей",
                        verbose_name="Количество проживающих людей",
                    ),
                ),
                (
                    "bed",
                    models.CharField(
                        choices=[
                            ("1 Односпальная", "1 Односпальная"),
                            ("1 Двуспальная", "1 Двуспальная"),
                            ("2 Односпальные", "2 Односпальные"),
                            ("2 Двуспальные", "2 Двуспальные"),
                            (
                                "1 Односпальная и 1 Двуспальная",
                                "1 Односпальная и 1 Двуспальная",
                            ),
                            (
                                "2 Односпальные и 1 Двуспальная",
                                "2 Односпальные и 1 Двуспальная",
                            ),
                            (
                                "2 Односпальные и 2 Двуспальные",
                                "2 Односпальные и 2 Двуспальные",
                            ),
                        ],
                        default="1 Односпальная",
                        help_text="Выберите кровать",
                        max_length=35,
                        verbose_name="Кровать",
                    ),
                ),
                (
                    "nightly_price",
                    models.PositiveIntegerField(
                        help_text="Введите цену", verbose_name="Цена"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Введите дату начала бронирования",
                        verbose_name="Дата начала бронирования",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Введите дату окончания бронирования",
                        verbose_name="Дата окончания бронирования",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите удобства в номере",
                        to="hotels.amenityroom",
                        verbose_name="Удобства в номере",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название отеля",
                        max_length=50,
                        verbose_name="Название отеля",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("1 Звезда", "1 Звезда"),
                            ("2 Звезды", "2 Звезды"),
                            ("3 Звезды", "3 Звезды"),
                            ("4 Звезды", "4 Звезды"),
                            ("5 Звезд", "5 Звезд"),
                        ],
                        default="5 Звезд",
                        help_text="Выберите категорию отеля",
                        max_length=20,
                        verbose_name="Категория отеля",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Введите страну", max_length=50, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Введите город", max_length=50, verbose_name="Город"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес отеля",
                        max_length=100,
                        verbose_name="Адрес отеля",
                    ),
                ),
                (
                    "distance_to_sea",
                    models.PositiveIntegerField(
                        help_text="Введите расстояние до моря",
                        verbose_name="Расстояние до моря",
                    ),
                ),
                (
                    "distance_to_airport",
                    models.PositiveIntegerField(
                        help_text="Введите расстояние до аэродрома",
                        verbose_name="Расстояние до аэродрома",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание отеля",
                        verbose_name="Описание отеля",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию отеля",
                        null=True,
                        upload_to="hotels/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "user_rating",
                    models.CharField(
                        blank=True,
                        help_text="Введите оценку",
                        max_length=255,
                        null=True,
                        verbose_name="Пользовательская оценка",
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(
                        choices=[
                            (datetime.time(14, 0), "14:00"),
                            (datetime.time(15, 0), "15:00"),
                            (datetime.time(16, 0), "16:00"),
                            (datetime.time(17, 0), "17:00"),
                            (datetime.time(18, 0), "18:00"),
                            (datetime.time(19, 0), "19:00"),
                            (datetime.time(20, 0), "20:00"),
                            (datetime.time(21, 0), "21:00"),
                            (datetime.time(22, 0), "22:00"),
                            (datetime.time(23, 0), "23:00"),
                            (datetime.time(0, 0), "00:00"),
                        ],
                        default="14:00",
                        help_text="Выберите время заезда",
                        max_length=8,
                        verbose_name="Время заезда",
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        choices=[
                            (datetime.time(0, 0), "00:00"),
                            (datetime.time(1, 0), "01:00"),
                            (datetime.time(2, 0), "02:00"),
                            (datetime.time(3, 0), "03:00"),
                            (datetime.time(4, 0), "04:00"),
                            (datetime.time(5, 0), "05:00"),
                            (datetime.time(6, 0), "06:00"),
                            (datetime.time(7, 0), "07:00"),
                            (datetime.time(8, 0), "08:00"),
                            (datetime.time(9, 0), "09:00"),
                            (datetime.time(10, 0), "10:00"),
                            (datetime.time(11, 0), "11:00"),
                            (datetime.time(12, 0), "12:00"),
                        ],
                        default="12:00",
                        help_text="Выберите время выезда",
                        max_length=8,
                        verbose_name="Время выезда",
                    ),
                ),
                (
                    "hotel_room",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rooms",
                        to="hotels.hotelroom",
                        verbose_name="Номера в отеле",
                    ),
                ),
                (
                    "place",
                    models.ManyToManyField(
                        help_text="Выберите тип размещения",
                        related_name="places",
                        to="hotels.placehotel",
                        verbose_name="Тип размещения",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите удобства в отеле",
                        to="hotels.amenityhotel",
                        verbose_name="Удобства в отеле",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отель",
                "verbose_name_plural": "Отели",
                "ordering": ["name"],
            },
        ),
    ]
