# Generated by Django 5.2.4 on 2025-07-03 11:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(blank=True, default='39.833333', help_text='Долгота (от -180 до 180)', null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='user_rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Пользовательская оценка', null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))], verbose_name='Пользовательская оценка'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='width',
            field=models.FloatField(blank=True, default='45.554477', help_text='Широта (от -90 до 90)', null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))], verbose_name='Широта'),
        ),
        migrations.AddIndex(
            model_name='typeofmeal',
            index=models.Index(fields=['hotel', 'name'], name='hotels_type_hotel_i_ddef4c_idx'),
        ),
    ]
