# Generated by Django 5.1.4 on 2024-12-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="hotel_room",
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_room",
            field=models.ManyToManyField(
                related_name="rooms",
                to="hotels.hotelroom",
                verbose_name="Номера в отеле",
            ),
        ),
    ]
