# Generated by Django 5.1.4 on 2024-12-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="place",
        ),
        migrations.AddField(
            model_name="hotel",
            name="place",
            field=models.ForeignKey(
                default="",
                help_text="Выберите тип размещения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="hotels.placehotel",
                verbose_name="Тип размещения",
            ),
            preserve_default=False,
        ),
    ]
