# Generated by Django 5.1.4 on 2024-12-12 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_remove_hotel_place_hotel_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="place",
            field=models.ForeignKey(
                help_text="Выберите тип размещения",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotels",
                to="hotels.placehotel",
                verbose_name="Тип размещения",
            ),
        ),
    ]
