# Generated by Django 5.1.4 on 2024-12-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_remove_hotel_hotel_room_hotel_hotel_room"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelroom",
            options={
                "ordering": ["category"],
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
            },
        ),
        migrations.AlterField(
            model_name="hotel",
            name="check_in_time",
            field=models.TimeField(
                help_text="Выберите время заезда",
                max_length=8,
                verbose_name="Время заезда",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="check_out_time",
            field=models.TimeField(
                help_text="Выберите время выезда",
                max_length=8,
                verbose_name="Время выезда",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию отеля",
                null=True,
                upload_to="hotels/",
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="user_rating",
            field=models.CharField(
                blank=True,
                help_text="Введите оценку",
                max_length=255,
                null=True,
                verbose_name="Пользовательская оценка",
            ),
        ),
        migrations.AlterField(
            model_name="hotelroom",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию номера",
                null=True,
                upload_to="hotels/rooms/",
                verbose_name="Фотография",
            ),
        ),
    ]
