# Generated by Django 5.1.4 on 2024-12-11 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelroom_options_alter_hotel_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(choices=[(datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00'), (datetime.time(0, 0), '00:00')], default='14:00', help_text='Выберите время заезда', max_length=8, verbose_name='Время заезда'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(1, 0), '01:00'), (datetime.time(2, 0), '02:00'), (datetime.time(3, 0), '03:00'), (datetime.time(4, 0), '04:00'), (datetime.time(5, 0), '05:00'), (datetime.time(6, 0), '06:00'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00')], default='12:00', help_text='Выберите время выезда', max_length=8, verbose_name='Время выезда'),
        ),
    ]
