# Generated by Django 5.2.5 on 2025-09-01 18:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('hotels', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, help_text='Загрузите документы по туру', null=True, upload_to='tour/documents', verbose_name='Документы')),
            ],
            options={
                'verbose_name': 'Документы по туру',
                'verbose_name_plural': 'Документы по турам',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Введите дату начала тура', verbose_name='Дата начала тура')),
                ('end_date', models.DateField(help_text='Введите дату окончания тура', verbose_name='Дата окончания тура')),
                ('departure_country', models.CharField(blank=True, help_text='Введите страну вылета', max_length=50, null=True, verbose_name='Страна вылета')),
                ('departure_city', models.CharField(blank=True, help_text='Введите город вылеты', max_length=50, null=True, verbose_name='Город вылета')),
                ('arrival_country', models.CharField(blank=True, help_text='Страну прибытия', max_length=50, null=True, verbose_name='Страна прибытия')),
                ('arrival_city', models.CharField(blank=True, help_text='Город прибытия', max_length=50, null=True, verbose_name='Город прибытия')),
                ('transfer', models.BooleanField(default=False, help_text='Отметьте использовать трансфер отельера', verbose_name='Использовать трансфер отельера')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Введите итоговую стоимость тура', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Итоговая стоимость тура')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина. Например 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))], verbose_name='Размер скидки на тур')),
                ('discount_start_date', models.DateField(blank=True, help_text='Введите дату начала скидки', null=True, verbose_name='Дата начала скидки')),
                ('discount_end_date', models.DateField(blank=True, help_text='Введите дату окончания скидки', null=True, verbose_name='Дата окончания скидки')),
                ('markup_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина. Например 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))], verbose_name='Наценка на тур')),
                ('publish_start_date', models.DateField(blank=True, help_text='Введите дату публикации тура', null=True, verbose_name='Дата публикации тура')),
                ('publish_end_date', models.DateField(blank=True, help_text='Введите дату снятия тура с публикации', null=True, verbose_name='Дата снятия тура с публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения')),
                ('is_active', models.BooleanField(default=True, help_text='Тур активен?', verbose_name='Тур активен?')),
                ('flight_from', models.ForeignKey(blank=True, help_text='Введите ID рейса возвращения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flight', verbose_name='Рейс возвращения')),
                ('flight_to', models.ForeignKey(blank=True, help_text='Введите ID рейса отправления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='flights.flight', verbose_name='Рейс отправления')),
                ('hotel', models.ForeignKey(blank=True, help_text='Введите ID отеля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='hotels.hotel', verbose_name='Отель')),
                ('rooms', models.ManyToManyField(blank=True, help_text='Введите ID номера', related_name='tours', to='rooms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ('start_date',),
            },
        ),
    ]
