# Generated by Django 5.1.4 on 2024-12-16 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flights", "0001_initial"),
        ("hotels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Укажите дату начала тура",
                        verbose_name="Дата начала тура",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Укажите дату окончания тура",
                        verbose_name="Дата окончания тура",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название тура",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Введите страну",
                        max_length=50,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Введите город",
                        max_length=50,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "type_of_holiday",
                    models.CharField(
                        blank=True,
                        help_text="Укажите тип отдыха",
                        max_length=100,
                        null=True,
                        verbose_name="Тип отдыха",
                    ),
                ),
                (
                    "meal_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Укажите стоимость питания",
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость питания",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Укажите стоимость тура",
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость тура",
                    ),
                ),
                (
                    "flight_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите обратный рейс",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flights.flight",
                        verbose_name="Рейс обратно",
                    ),
                ),
                (
                    "flight_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите рейс туда",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours",
                        to="flights.flight",
                        verbose_name="Рейс туда",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите отель",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours",
                        to="hotels.hotel",
                        verbose_name="Отель",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите номер",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours",
                        to="hotels.room",
                        verbose_name="Номер",
                    ),
                ),
                (
                    "tour_operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите туроператора",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Туроператор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тур",
                "verbose_name_plural": "Туры",
                "ordering": ("start_date",),
            },
        ),
    ]
