# Generated by Django 5.2.5 on 2025-09-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_operator',
            field=models.ForeignKey(blank=True, help_text='Введите ID туроператора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to=settings.AUTH_USER_MODEL, verbose_name='Туроператор'),
        ),
        migrations.AddField(
            model_name='tour',
            name='type_of_meals',
            field=models.ManyToManyField(blank=True, help_text='Выберите типы питания, который есть в этом отеле для этого тура', related_name='tours', to='hotels.typeofmeal', verbose_name='Типы питания'),
        ),
        migrations.AddField(
            model_name='tourdocument',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Документы по туру', on_delete=django.db.models.deletion.CASCADE, related_name='tour_documents', to='tours.tour', verbose_name='Документы по туру'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['publish_start_date', 'publish_end_date'], name='idx_tours_dates'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['hotel_id'], name='idx_tours_hotel'),
        ),
    ]
