# Generated by Django 5.2.4 on 2025-07-21 18:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина. Например 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))], verbose_name='Размер скидки на тур'),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_end_date',
            field=models.DateField(blank=True, help_text='Введите дату окончания скидки', null=True, verbose_name='Дата окончания скидки'),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_start_date',
            field=models.DateField(blank=True, help_text='Введите дату начала скидки', null=True, verbose_name='Дата начала скидки'),
        ),
        migrations.AddField(
            model_name='tour',
            name='markup_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите размер скидки, где 0.01 - это 1%, 1.00 - это 100%, а всё что больше 1.00 - это уже величина. Например 0.53 - это 53%, а 2000 - это величина скидки в виде 2000 рублей.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))], verbose_name='Наценка на тур'),
        ),
        migrations.AddField(
            model_name='tour',
            name='publish_end_date',
            field=models.DateField(blank=True, help_text='Введите дату снятия тура с публикации', null=True, verbose_name='Дата снятия тура с публикации'),
        ),
        migrations.AddField(
            model_name='tour',
            name='publish_start_date',
            field=models.DateField(blank=True, help_text='Введите дату публикации тура', null=True, verbose_name='Дата публикации тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите итоговую стоимость тура', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Итоговая стоимость тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='transfer',
            field=models.BooleanField(default=False, help_text='Отметьте использовать трансфер отельера', verbose_name='Использовать трансфер отельера'),
        ),
        migrations.DeleteModel(
            name='TourStock',
        ),
    ]
