# Generated by Django 5.2.3 on 2025-06-30 14:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Введите номер рейса в формате: AA XXXX, или AX XXX, где A-латинские буквы в верхнем регистре, X- цифры', max_length=10, verbose_name='Номер рейса')),
                ('airline', models.CharField(help_text='Введите название авиакомпании', max_length=100, verbose_name='Авиакомпания')),
                ('departure_country', models.CharField(blank=True, help_text='Введите страну вылета', max_length=50, null=True, verbose_name='Страна вылета')),
                ('departure_city', models.CharField(blank=True, help_text='Введите город вылета', max_length=50, null=True, verbose_name='Город вылета')),
                ('departure_airport', models.CharField(help_text='Введите аэропорт вылета', max_length=100, verbose_name='Аэропорт вылета')),
                ('arrival_country', models.CharField(blank=True, help_text='Введите страна прибытия', max_length=50, null=True, verbose_name='Страна прибытия')),
                ('arrival_city', models.CharField(blank=True, help_text='Введите город прибытия', max_length=50, null=True, verbose_name='Город прибытия')),
                ('arrival_airport', models.CharField(help_text='Введите аэропорт прибытия', max_length=100, verbose_name='Аэропорт прибытия')),
                ('departure_date', models.DateField(help_text='Введите дату вылета', verbose_name='Дата вылета')),
                ('departure_time', models.TimeField(help_text='Введите время вылета', verbose_name='Время вылета')),
                ('arrival_date', models.DateField(help_text='Введите дату прибытия', verbose_name='Дата прибытия')),
                ('arrival_time', models.TimeField(help_text='Введите время прибытия', verbose_name='Время прибытия')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену билета для взрослого', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('price_for_child', models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену билета для ребенка', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена для ребенка')),
                ('service_class', models.CharField(default='Эконом', help_text='Введите класс обслуживания', max_length=100, verbose_name='Класс обслуживания')),
                ('flight_type', models.CharField(default='Регулярный', help_text='Введите тип рейса', max_length=50, verbose_name='Тип рейса')),
                ('description', models.TextField(blank=True, help_text='Багаж, ручная кладь, питание на борту, сайт авиакомпании', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ('departure_date',),
            },
        ),
    ]
