# Generated by Django 5.1.4 on 2024-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.PositiveIntegerField(
                        help_text="Введите номер рейса", verbose_name="Номер рейса"
                    ),
                ),
                (
                    "airline",
                    models.CharField(
                        help_text="Введите название авиакомпании",
                        max_length=100,
                        verbose_name="Авиакомпания",
                    ),
                ),
                (
                    "departure_airport",
                    models.CharField(
                        help_text="Укакжите аэропорт вылета",
                        max_length=100,
                        verbose_name="Аэропорт вылета",
                    ),
                ),
                (
                    "arrival_airport",
                    models.CharField(
                        help_text="Укакжите аэропорт прибытия",
                        max_length=100,
                        verbose_name="Аэропорт прибытия",
                    ),
                ),
                (
                    "departure_date",
                    models.DateField(
                        help_text="Укакжите дату вылета", verbose_name="Дата вылета"
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        help_text="Укажите время вылета", verbose_name="Время вылета"
                    ),
                ),
                (
                    "arrival_date",
                    models.DateField(
                        help_text="Укакжите дату прибытия", verbose_name="Дата прибытия"
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        help_text="Укажите время прибытия",
                        verbose_name="Время прибытия",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите цену билета",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейс",
                "verbose_name_plural": "Рейсы",
                "ordering": ["departure_date"],
            },
        ),
    ]
