# Generated by Django 5.1.4 on 2024-12-24 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(
                        help_text="Введите номер рейса",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите номер рейса в формате: AA XXXX, где A-латинские буквы в верхнем регистре, X- цифры от 0 до 9)",
                                regex="^[A-Z]{2} [0-9]{4}$",
                            )
                        ],
                        verbose_name="Номер рейса",
                    ),
                ),
                (
                    "airline",
                    models.CharField(
                        choices=[
                            ("Аэрофлот", "Аэрофлот"),
                            ("Победа", "Победа"),
                            ("Россия", "Россия"),
                            ("S7", "S7"),
                            ("Уральские авиалинии", "Уральские авиалинии"),
                            ("Северный ветер", "Северный ветер"),
                            ("Turkish airlines", "Turkish airlines"),
                            ("Emirates", "Emirates"),
                            ("Азимут", "Азимут"),
                            ("Red Wings", "Red Wings"),
                            ("UTair", "UTair"),
                            ("Ямал", "Ямал"),
                            ("Pegasus Airlines", "Pegasus Airlines"),
                            ("Azur Air", "Azur Air"),
                            ("Corendon Airlines", "Corendon Airlines"),
                            ("Air Arabia", "Air Arabia"),
                            ("Fly Dubai", "Fly Dubai"),
                            ("China Southern Airlines", "China Southern Airlines"),
                            ("China Eastern", "China Eastern"),
                            ("Sichuan Airlines", "Sichuan Airlines"),
                            ("Qatar Airways", "Qatar Airways"),
                            ("Белавиа", "Белавиа"),
                        ],
                        help_text="Введите название авиакомпании",
                        max_length=100,
                        verbose_name="Авиакомпания",
                    ),
                ),
                (
                    "departure_airport",
                    models.CharField(
                        help_text="Укажите аэропорт вылета",
                        max_length=100,
                        verbose_name="Аэропорт вылета",
                    ),
                ),
                (
                    "arrival_airport",
                    models.CharField(
                        help_text="Укажите аэропорт прибытия",
                        max_length=100,
                        verbose_name="Аэропорт прибытия",
                    ),
                ),
                (
                    "departure_date",
                    models.DateField(
                        help_text="Укажите дату вылета", verbose_name="Дата вылета"
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        help_text="Укажите время вылета", verbose_name="Время вылета"
                    ),
                ),
                (
                    "arrival_date",
                    models.DateField(
                        help_text="Укажите дату прибытия", verbose_name="Дата прибытия"
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        help_text="Укажите время прибытия",
                        verbose_name="Время прибытия",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите цену билета",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "service_class",
                    models.CharField(
                        choices=[
                            ("Эконом", "Эконом"),
                            ("Бизнес ", "Бизнес"),
                            ("Первый", "Первый"),
                        ],
                        default="Э",
                        max_length=100,
                        verbose_name="Класс обслуживания",
                    ),
                ),
                (
                    "flight_type",
                    models.CharField(
                        choices=[
                            ("Регулярный", "Регулярный"),
                            ("Чартерный", "Чартерный"),
                            ("Транзитный", "Транзитный"),
                        ],
                        default="Р",
                        max_length=50,
                        verbose_name="Тип рейса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейс",
                "verbose_name_plural": "Рейсы",
                "ordering": ("departure_date",),
            },
        ),
    ]
