# Generated by Django 5.1.4 on 2024-12-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(
                help_text="Введите номер рейса",
                max_length=10,
                verbose_name="Номер рейса",
            ),
        ),
    ]
