# Generated by Django 5.1.4 on 2024-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_alter_flight_flight_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={
                "ordering": ("departure_date",),
                "verbose_name": "Рейс",
                "verbose_name_plural": "Рейсы",
            },
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_airport",
            field=models.CharField(
                help_text="Укажите аэропорт прибытия",
                max_length=100,
                verbose_name="Аэропорт прибытия",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_date",
            field=models.DateField(
                help_text="Укажите дату прибытия", verbose_name="Дата прибытия"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_airport",
            field=models.CharField(
                help_text="Укажите аэропорт вылета",
                max_length=100,
                verbose_name="Аэропорт вылета",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_date",
            field=models.DateField(
                help_text="Укажите дату вылета", verbose_name="Дата вылета"
            ),
        ),
    ]
