# Generated by Django 5.2.5 on 2025-09-01 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('date_born', models.DateField(help_text='Формат: YYYY-MM-DD', verbose_name='Дата рождения')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('russian_passport_no', models.CharField(blank=True, help_text='Формат: XXXX XXXXXX', null=True, validators=[django.core.validators.RegexValidator(message='Введите серия/номер в формате: XXXX XXXXXX', regex='^[0-9]{4} [0-9]{6}$')], verbose_name='Серия/номер российского паспорта')),
                ('international_passport_no', models.CharField(blank=True, help_text='Формат: XX XXXXXXXX', null=True, validators=[django.core.validators.RegexValidator(message='Введите серия/номер в формате: XX XXXXXXXX', regex='^[0-9]{2} [0-9]{7}$')], verbose_name='Серия/номер иностранного паспорта')),
                ('validity_international_passport', models.DateField(blank=True, help_text='Формат: DD-MM-YYYY', null=True, verbose_name='Срок действия иностранного паспорта')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'ordering': ('lastname',),
            },
        ),
    ]
