# Generated by Django 5.2.4 on 2025-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_born',
            field=models.DateField(help_text='Формат: YYYY-MM-DD', verbose_name='Дата рождения'),
        ),
    ]
