# Generated by Django 5.2.5 on 2025-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email туриста, на который будет отправляться рассылка.', max_length=254, unique=True, verbose_name='Email для рассылки.')),
                ('mailing', models.BooleanField(default=False, help_text='Да/Нет', verbose_name='Подписка на рассылку.')),
            ],
            options={
                'verbose_name': 'Рассылка писем',
                'verbose_name_plural': 'Рассылки писем',
            },
        ),
    ]
