# Generated by Django 5.2.4 on 2025-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='email',
            field=models.EmailField(help_text='Email туриста, на который будет отправляться рассылка.', max_length=254, unique=True, verbose_name='Email для рассылки.'),
        ),
    ]
